apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m
  chart:
    spec:
      chart: base
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  install:
    createNamespace: true
